<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
/**
 * @var Mage_Page_Block_Html_Header $this
 */
?>
        
		<!--<div class="brand">-->
    <?php if ($this->getIsHomePage()): ?>
    <?php /*?>
        <h1 class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a></h1>
     <?php */?>
    <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="active"><strong><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></strong></a>
    <?php else: ?>
        <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class=""><strong><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></strong></a>
    <?php endif ?>
<!--</div>-->
<?php /*?>
    <p class="welcome-msg"><?php echo $this->getWelcome() ?> <?php echo $this->getAdditionalHtml() ?></p>
<?php */?>
                
<?php //echo $this->getChildHtml('topContainer'); ?>
<div class="navbar">
<div class="navbar-inner">
<div class="container">
<a class="brand hidden-desktop" href="javascript:void(0)" data-toggle="collapse" data-target=".nav-collapse">Menu</a>
<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
</a>
<div class="nav-collapse">
<?php echo $this->getChildHtml('topMenu') ?>
<?php echo $this->getChildHtml('topSearch') ?>
</div><!--/.nav-collapse -->
</div>
</div>
</div>